### ISSUE TITLE
SQL max degree of parallelism should be set to 1 (SQL default is 0) for Sharepoint 2016 Products Configuration Wizard

### ISSUE THREAD

**Issue by rviersel** [MicrosoftDocs/MIMDocs#219]
No mention about the max degree of parallelism on SQL which should be set to 1, otherwise Sharepoint 2016 Products Configuration Wizard will throw below error.
After changing the properties op the SQL instance, setting it to 1, and restarting the SQL instance, the Sharepoint configuration wizard was able to continue successfully.

-------------------------------------

Failed to create the configuration database.
An exception of type Microsoft.SharePoint.SPException was thrown.  Additional exception information: This SQL Server instance does not have the required "max degree of parallelism" setting of 1. Database provisioning operations will continue to fail if "max degree of parallelism" is not set 1 or the current account does not have permissions to change the setting.  See documentation for details on manually changing the setting.
Microsoft.SharePoint.SPException: This SQL Server instance does not have the required "max degree of parallelism" setting of 1. Database provisioning operations will continue to fail if "max degree of parallelism" is not set 1 or the current account does not have permissions to change the setting.  See documentation for details on manually changing the setting.
   at Microsoft.SharePoint.Administration.SPDatabase.Provision(SPDatabase database, SafeSqlConnectionStringBuilder connectionString, SqlFile sqlFileId, Dictionary`2 options)
   at Microsoft.SharePoint.Administration.SPConfigurationDatabase.Provision(SqlConnectionStringBuilder connectionString)
   at Microsoft.SharePoint.Administration.SPFarmFactory.CreateConfigurationDatabase()
   at Microsoft.SharePoint.Administration.SPFarmFactory.Create()
   at Microsoft.SharePoint.Administration.SPFarm.Create(SqlConnectionStringBuilder configurationDatabase, SqlConnectionStringBuilder administrationContentDatabase, SqlConnectionStringBuilder siteMapDatabase, IdentityType identityType, String farmUser, SecureString farmPassword, SecureString masterPassphrase)
   at Microsoft.SharePoint.PostSetupConfiguration.ConfigurationDatabaseTask.CreateOrConnectConfigDb()
   at Microsoft.SharePoint.PostSetupConfiguration.ConfigurationDatabaseTask.Run()
   at Microsoft.SharePoint.PostSetupConfiguration.TaskThread.ExecuteTask()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5faf70f-a9fe-6fa8-9465-968550ee71a2
* Version Independent ID: 1599edaa-287f-c250-585c-14d67069613d
* Content: [Deploy PAM step 3 – PAM server](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/step-3-prepare-pam-server)
* Content Source: [MIMDocs/pam/step-3-prepare-pam-server.md](https://github.com/Microsoft/MIMDocs/blob/master/MIMDocs/pam/step-3-prepare-pam-server.md)
* Product: **microsoft-identity-manager**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
The following issue is being closed due to the age. If this is still an issue, please re-submit this. Thank you.

#please-close
